MVIKotlin-169 Replace Serializable with Parcelize
badoo/MVIKotlin pull request #172
Opened 2020-12-08 17:02 UTC by LDuncAndroid

- TodoDetailsFragment now implements Parcelable opposed to Serializable

2020-12-08 23:04 UTC, arkivanov requested changes

2020-12-08 23:04 UTC, arkivanov commented on sample/todo-app-android/src/main/java/com/arkivanov/mvikotlin/sample/todo/android/details/TodoDetailsFragment.kt
> +        }.let {
Looks like this `let` is useless, can be just `.getParcelable...`

2020-12-08 23:04 UTC, arkivanov commented on sample/todo-app-android/src/main/java/com/arkivanov/mvikotlin/sample/todo/android/details/TodoDetailsFragment.kt
> +        override fun describeContents(): Int = 0
The original idea was to use `@Parcelize`. Now since Kotlin 1.4.20 it is available via [kotlin-parcelize](https://developer.android.com/kotlin/parcelize) plugin. I have submitted #174 with Kotlin update to 1.4.20. Once merged, you can use the `kotlin-parcelize` plugin. You will need to add `id("kotlin-parcelize")` [here](https://github.com/arkivanov/MVIKotlin/blob/abd23133cf06b8ee3a6a9cffb81ac511fd1e5291/sample/todo-app-android/build.gradle.kts#L3). After that you can annotate `Arguments` with `@Parcelize` and remove the implementation.

2020-12-08 23:46 UTC, LDuncAndroid commented on sample/todo-app-android/src/main/java/com/arkivanov/mvikotlin/sample/todo/android/details/TodoDetailsFragment.kt
> +        }.let {
Will fix :+1:

2020-12-08 23:48 UTC, LDuncAndroid commented on sample/todo-app-android/src/main/java/com/arkivanov/mvikotlin/sample/todo/android/details/TodoDetailsFragment.kt
> +        override fun describeContents(): Int = 0
I purposefully avoided using it as I thought you might want a concrete implementation. I should've taken the easy route :smile:

Will fix :+1:

2020-12-08 23:58 UTC, arkivanov commented on sample/todo-app-android/src/main/java/com/arkivanov/mvikotlin/sample/todo/android/details/TodoDetailsFragment.kt
> +        override fun describeContents(): Int = 0
Kotlin 1.4.20 update has merged. You can now update your branch and use `kotlin-parcelize` plugin.

2020-12-09 00:49 UTC, LDuncAndroid commented on sample/todo-app-android/src/main/java/com/arkivanov/mvikotlin/sample/todo/android/details/TodoDetailsFragment.kt
> +        override fun describeContents(): Int = 0
Not sure what the etiquette is for resolving this conversation, I don't contribute much to OSS.

2020-12-09 15:16 UTC, arkivanov commented on sample/todo-app-android/src/main/java/com/arkivanov/mvikotlin/sample/todo/android/details/TodoDetailsFragment.kt
> +        override fun describeContents(): Int = 0
That's ok, you can just write a response.

2020-12-09 15:16 UTC, arkivanov approved these changes

2020-12-09 15:17 UTC, merged