Fix wrong adb path selection
badoo/MVIKotlin pull request #281
Opened 2021-09-04 11:29 UTC by ema987

First of all, thank you very much for this **amazing** project!

Issue description: 
- use the standalone app or the IntelliJ Idea plugin for time travelling
- start time travelling by clicking the debug icon
- select an executable which is not `adb`
- the app/plugin still try to execute it without successful result
- try to start again the time travelling by clicking the debug icon, the app/plugin still tries to launch the executable selected earlier (which is not `adb`) ending in an error. 

Now you can't anymore select the right `adb` executable and you're stuck with an unusable app/plugin.

It looks like to me the right checks are in place to avoid select an executable which is not `adb` in the file selection dialogs but the filters/checks are not respected, at least on my Macbook with BigSur 11.4 and IntelliJIdea plugin version 3.0.0-alpha01.

I improved the `adb` path selection manually checking a file named `adb` is selected in the file selection dialog.
Furthermore, everytime you start debugging, the code checks the selected path is an `adb` executable, otherwise it prompts you the file selection dialog.

This is a quick fix and unfortunately duplicated in some places.

IMHO, in a future version, it would be better to create a new button to make the user able to select the `adb` path anytime, so it can be changed when needed and some checks can be removed.

I hope this is useful!

2021-09-04 15:43 UTC, arkivanov requested changes

2021-09-04 15:43 UTC, arkivanov commented on mvikotlin-timetravel-client/app-desktop/src/jvmMain/kotlin/com/arkivanov/mvikotlin/timetravel/client/desktop/Main.kt
> +private fun isValidAdbExecutable(file: File): Boolean {
This function can be shared in `client-internal` module, under `jvmMain` source set, `com.arkivanov.mvikotlin.timetravel.client.internal.utils` package. It can be also made as extension function, to simplify its usages.

2021-09-04 15:43 UTC, arkivanov commented on mvikotlin-timetravel-client/app-desktop/src/jvmMain/kotlin/com/arkivanov/mvikotlin/timetravel/client/desktop/Main.kt
> -    dialog.filenameFilter = FilenameFilter { _, name -> name == "adb" }
Why this file name filter is removed? It worked at least on Ubuntu.

2021-09-04 15:43 UTC, arkivanov commented on mvikotlin-timetravel-client/app-desktop/src/jvmMain/kotlin/com/arkivanov/mvikotlin/timetravel/client/desktop/Main.kt
> +    return if(selectedFile!= null && isValidAdbExecutable(selectedFile)) {
The function `isValidAdbExecutable` can be extension, so this can be converted to:
```kotlin
return dialog
    .selectedFile
    ?.takeIf(File::isValidAdbExecutable)
    ?.absolutePath
```

2021-09-04 15:43 UTC, arkivanov commented on mvikotlin-timetravel-client/plugin-idea/src/main/java/com/arkivanov/mvikotlin/plugin/idea/timetravel/TimeTravelToolWindow.kt
> +        return if(path != null && isValidAdbExecutable(File(path))) {
Same here, once `isValidAdbExecutable` is shared, can be something like:
```kotlin
        chooseFile(
            ...
        )
            ?.path
            ?.takeIf { File(it).isValidAdbExecutable() }

```

2021-09-04 15:45 UTC, arkivanov commented
Thank you very much for the fix! Seems like on macOS the file name filter is ignored and you can actually select any file. On Ubuntu (my machine) it works fine and allows only `adb` files to be selected.

2021-09-04 18:10 UTC, ema987 commented on mvikotlin-timetravel-client/app-desktop/src/jvmMain/kotlin/com/arkivanov/mvikotlin/timetravel/client/desktop/Main.kt
> -    dialog.filenameFilter = FilenameFilter { _, name -> name == "adb" }
Didn't know it works on Ubuntu. Restored it

2021-09-04 18:12 UTC, ema987 commented on mvikotlin-timetravel-client/app-desktop/src/jvmMain/kotlin/com/arkivanov/mvikotlin/timetravel/client/desktop/Main.kt
> +private fun isValidAdbExecutable(file: File): Boolean {
Today I didn't see `jvmMain` that's why I replicated the code. Now there is an extension function to check the path

2021-09-04 18:12 UTC, ema987 commented on mvikotlin-timetravel-client/app-desktop/src/jvmMain/kotlin/com/arkivanov/mvikotlin/timetravel/client/desktop/Main.kt
> +    return if(selectedFile!= null && isValidAdbExecutable(selectedFile)) {
Done

2021-09-04 18:12 UTC, ema987 commented on mvikotlin-timetravel-client/plugin-idea/src/main/java/com/arkivanov/mvikotlin/plugin/idea/timetravel/TimeTravelToolWindow.kt
> +        return if(path != null && isValidAdbExecutable(File(path))) {
Done

2021-09-04 18:13 UTC, ema987 commented
Thank you for the fast response! The code should now be fixed as you asked

2021-09-09 08:17 UTC, arkivanov approved these changes

2021-09-09 08:17 UTC, merged

2021-09-09 08:17 UTC, arkivanov commented
Thanks for your contribution!