Update time travel documentation to describe the feature in more detail
badoo/MVIKotlin pull request #297
Opened 2021-10-12 06:31 UTC by plusmobileapps

# Overview 

Update the time travel documentation based off some of the [discussion](https://github.com/arkivanov/MVIKotlin/discussions/289)

## Issue 

Closes #292

2021-10-12 09:29 UTC, arkivanov requested changes

2021-10-12 09:29 UTC, arkivanov commented on docs/time_travel.md
> +If using the time travel plugin or desktop app for debugging described later in this document, then the `TimeTravelServer` needs to be running on the Android or iOS application. The default port of t
Not necessarily Android or iOS, the `TimeTravelServer` currently supports `android`, `jvm` and all Darwin targets. Maybe write it somehow differently? E.g. "needs to be running on an application being debugged" or something like that?

2021-10-12 09:29 UTC, arkivanov commented on docs/time_travel.md
> +#### Setup TimeTravelServer Android
Would be good to also add a section for normal JVM app setup. There is no any sample available, as far as I know. But it is very similar to Android, except the `TimeTravelServer` should be started somewhere in `fun main()`. A closest sample can be found in the JB [TodoApp](https://github.com/JetBrains/compose-jb/blob/162813c86485dd7fca528ea8ef41589e9e8195a7/examples/todoapp/desktop/src/jvmMain/kotlin/example/todo/desktop/Main.kt#L56). So basically same approach, just create the `TimeTravelServer` if needed.

2021-10-12 09:29 UTC, arkivanov commented on docs/time_travel.md
> +#### Setup TimeTravelServer iOS
Again, not only iOS. Maybe "Darwin" or "Apple"?

2021-10-12 09:29 UTC, arkivanov commented on docs/time_travel.md
> +To setup the `TimeTravelServer` on iOS, the `mvikotlin-timetravel` dependency must be exported into the shared module from the [`build.gradle.kts`](https://github.com/arkivanov/MVIKotlin/blob/4e06249
Worth to mention that the dependency should be also [added](https://github.com/arkivanov/MVIKotlin/blob/4e0624946fe24a2fc47ecbfeb35a6fecaf09f709/sample/todo-darwin-umbrella/build.gradle.kts#L13) as `api`.

2021-10-12 09:29 UTC, arkivanov commented on docs/time_travel.md
> +To connect the time travel client to an iOS emulator, open up the time travel client settings. Make sure the "Connect via ADB" is unchecked and host is `localhost`. Save the settings and link to the
It is "simulator" AFAIK, not "emulator".

2021-10-14 05:50 UTC, plusmobileapps commented on docs/time_travel.md
> +#### Setup TimeTravelServer Android
Is there something I am missing in trying to add the `TimeTravelServer` to the todo app? I cannot seem to get the desktop time travel app to connect with the todo app 🤔   [commit](https://github.com/plusmobileapps/compose-jb/commit/505fb2fd54483217667737abf1f992d7f0c180c8)

2021-10-14 18:45 UTC, arkivanov commented on docs/time_travel.md
> +#### Setup TimeTravelServer Android
Yeah, you basically didn't implement the `runOnMainThread` function. It can be implemented using `SwingUtilities.invokeLater`, or using coroutines if they are used in the project.

2021-10-15 06:26 UTC, plusmobileapps commented on docs/time_travel.md
> +#### Setup TimeTravelServer Android
Interesting, I was thrown off by that function because I don't remember needing to implement that for the other platforms. I could get it working though, what is that used for exactly? 

```kotlin
    val timeTravelServer = TimeTravelServer(runOnMainThread = {
        SwingUtilities.invokeLater(it)
    })
    timeTravelServer.start()
```

2021-10-15 06:34 UTC, plusmobileapps commented on docs/time_travel.md
> +```
Let me know if there is something else that should be added for the JVM

2021-10-15 08:17 UTC, arkivanov commented on docs/time_travel.md
> +#### Setup TimeTravelServer Android
Android has `Handler`, for Darwin targets there is `dispatch_get_main_queue`. But there nothing like this for the pure JVM target, it depends on the framework used by the client. So at the moment we have to provide it via DI.

2021-10-15 08:20 UTC, arkivanov approved these changes

2021-10-15 08:20 UTC, merged

2021-10-15 08:21 UTC, arkivanov commented
Big thanks for this!