Sample js
badoo/MVIKotlin pull request #58
Opened 2020-05-19 19:37 UTC by maxtox3

2020-05-20 21:37 UTC, arkivanov requested changes

2020-05-20 21:37 UTC, arkivanov commented on mvikotlin/src/commonMain/kotlin/com/arkivanov/mvikotlin/core/store/Store.kt
> +    @JsName("dispose")
`@JsName` is useful only for methods with arguments. Can be removed.

2020-05-20 21:37 UTC, arkivanov commented on sample/todo-app-js/build.gradle.kts
> +kotlin.target.browser {}
Please enable `Settings -> General -> Ensure line feed ...`  setting in IDEA and make sure every file has a blank line at the end.

2020-05-20 21:37 UTC, arkivanov commented on sample/todo-app-js/src/main/kotlin/LifecycleConsumer.kt
> +interface LifecycleConsumer<in T>: LifecycleOwner {
`LifecycleConsumer` is a confusing name, since it sounds like it consumes a life cycle, but in fact it consumes values. In Android I named this `LifecycledConsumer`, let's use the same name here?

2020-05-20 21:37 UTC, arkivanov commented on sample/todo-app-js/src/main/kotlin/Util.kt
> +val storeFactoryInstance =
I don't have Detekt setup yet. Please specify the return type.

2020-05-20 21:37 UTC, arkivanov commented on sample/todo-app-js/src/main/kotlin/Util.kt
> +val frameWorkType = FrameworkType.REAKTIVE
Return type

2020-05-20 21:37 UTC, arkivanov commented on sample/todo-app-js/src/main/kotlin/Util.kt
> +val frameWorkType = FrameworkType.REAKTIVE
Typo: `frameworkType`

2020-05-20 21:37 UTC, arkivanov commented on sample/todo-app-js/src/main/kotlin/details/TodoDetailsComponent.kt
> +        val onClose: () -> Unit
`TodoDetailsController.Output` already has `Finished`, can we reuse it?

2020-05-20 21:37 UTC, arkivanov commented on sample/todo-app-js/src/main/kotlin/details/TodoDetailsViewProxy.kt
> +    fun dispatchEvent(event: TodoDetailsView.Event) {
You can just override `dispatch` and make it public

2020-05-20 21:37 UTC, arkivanov commented on sample/todo-app-js/src/main/kotlin/list/TodoAddViewProxy.kt
> +    fun dispatchEvent(event: TodoAddView.Event) {
Same here, override `dispatch` and make it public

2020-05-20 21:37 UTC, arkivanov commented on sample/todo-app-js/src/main/kotlin/root/LifecycleWrapper.kt
> +    fun start() {
I thought React Component`s life cycle is richer. Does it have stopped state? Like if browser is minimized.

2020-05-20 21:37 UTC, arkivanov commented on sample/todo-common/src/jsMain/kotlin/TodoDatabaseImpl.kt
> +class TodoDatabaseImpl : TodoDatabase {
We can have a single implementation for Native and JS if you put this implementation into `jsNativeCommonMain` source set. If so then you can delete `TodoDatabaseImpl` from the `darwinCommonMain` source set.

2020-05-20 21:37 UTC, arkivanov commented on sample/todo-app-js/src/main/kotlin/details/TodoDetailsComponent.kt
> +import react.*
Please no wildcard imports. Same for other files. You can use these settings
![image](https://user-images.githubusercontent.com/26204457/82499849-54907700-9aea-11ea-8476-0c9fa298f77a.png)

2020-05-20 21:40 UTC, arkivanov commented
Please also add the new `:sample:todo-app-js` module to the build pipeline. Assuming the build task should be `:sample:todo-app-js:build` you can apply the following patch:
```
Index: .github/workflows/build.yml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- .github/workflows/build.yml	(date 1589975473000)
+++ .github/workflows/build.yml	(date 1590010741000)
@@ -18,7 +18,7 @@
       - name: Install dependencies
         run: sudo apt-get install nodejs chromium-browser
       - name: Build JVM, Android, JS
-        run: ./gradlew :utils-internal:build :rx:build :rx-internal:build :mvikotlin:build :mvikotlin-test-internal:build :mvikotlin-main:build :mvikotlin-logging:build :mvikotlin-timetravel:build :mvikotlin-timetravel-proto-internal:build :mvikotlin-timetravel-plugin-idea:build :mvikotlin-extensions-reaktive:build :mvikotlin-extensions-coroutines:build :androidx-lifecycle-interop:build :sample:todo-app-android:assembleDebug -Pbuild_type=NON_NATIVE
+        run: ./gradlew :utils-internal:build :rx:build :rx-internal:build :mvikotlin:build :mvikotlin-test-internal:build :mvikotlin-main:build :mvikotlin-logging:build :mvikotlin-timetravel:build :mvikotlin-timetravel-proto-internal:build :mvikotlin-timetravel-plugin-idea:build :mvikotlin-extensions-reaktive:build :mvikotlin-extensions-coroutines:build :androidx-lifecycle-interop:build :sample:todo-app-android:assembleDebug :sample:todo-app-js:build -Pbuild_type=NON_NATIVE
   linux-build:
     name: Build Linux
     runs-on: ubuntu-latest
```

2020-05-20 21:41 UTC, arkivanov commented on mvikotlin/src/commonMain/kotlin/com/arkivanov/mvikotlin/core/store/Store.kt
> +    @JsName("dispose")
Perhaps you need to merge master

2020-05-20 23:35 UTC, arkivanov commented
Just for your information, currently Details screen is not closed when the delete button is clicked. I will fix it in common code. In general `Output.Finished` event should be dispatched.

2020-05-20 23:37 UTC, arkivanov commented on sample/todo-app-js/src/main/kotlin/Util.kt
> +        LoggingStoreFactory(delegate = TimeTravelStoreFactory(fallback = DefaultStoreFactory))
So there is no UI for time travel right?

2020-05-22 20:41 UTC, maxtox3 commented on sample/todo-app-js/src/main/kotlin/root/LifecycleWrapper.kt
> +    fun start() {
Nothing happens with page when browser is minimized

2020-05-22 20:58 UTC, arkivanov commented on sample/todo-app-js/src/main/kotlin/root/LifecycleWrapper.kt
> +    fun start() {
There is `document["hidden"]` property that I used in the Reaktive sample here: https://github.com/badoo/Reaktive/blob/b901a77f0c456161b72b2445124ff5ffc6e1b98b/sample-js-browser-app/src/main/kotlin/com/badoo/main.kt#L28
`document.addEventListener("visibilitychange", { ... })` can be to listen for the change.

But if you are sure about React then I'm ok.

2020-05-22 21:33 UTC, maxtox3 commented on sample/todo-app-js/src/main/kotlin/Util.kt
> +        LoggingStoreFactory(delegate = TimeTravelStoreFactory(fallback = DefaultStoreFactory))
removed from build.gradle.kts and in Utils.kt

2020-05-23 11:47 UTC, arkivanov approved these changes

2020-05-23 11:47 UTC, merged